### ISSUE TITLE
 snake slam cannot be visualized, is the code complete?

### ISSUE THREAD

**Issue by yuancaimaiyi** [darglein/Snake-SLAM#4]
@darglein 

When I run snake slam, saiga doesn't visualize the tracking result of the slam, saiga is black and nothing!!!!!!!!!
![view](https://user-images.githubusercontent.com/28293910/164432506-2fe7c571-3abb-4c7e-84bd-f63e61cf7308.png)

**Comment by darglein** [comment]
Please check again the latest commits!

**Comment by yuancaimaiyi** [comment]
@darglein 
Hi,latest commit can visualize the tracking result of the slam,thanks. but the map p cannot be zoomed。
![image](https://user-images.githubusercontent.com/28293910/167088878-edb421c8-3e74-442e-9abc-195bffd39008.png)

**Comment by darglein** [comment]
Try with WASD on the keyboard, and Middle-Mouse Drag and Drop.

I'll close this issue as original problem is solved.
